# This file defines the infrastructure services needed for local development.
# It allows us to start our entire backend environment with a single command.
services:
  # -------------------- DATABASE --------------------
  # Defines our primary PostgreSQL database service.
  postgres:
    image: postgres:16-alpine
    container_name: payments_postgres
    environment:
      # These variables configure the database on its first run.
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments_db
    ports:
      # Maps your local machine's port 5432 to the container's port 5432.
      - "5432:5432"
    volumes:
      # Persists the database data on your machine, so it's not lost when the container stops.
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # -------------------- LEDGER SERVICE (Go) --------------------
  ledger-service:
    build:
      context: ../services/ledger-service # Tells Docker to build from the Dockerfile in this path
    container_name: payments_ledger
    ports:
      - "8082:8082" # Maps your port 8082 to the container's port 8082
    environment:
      - LEDGER_SERVICE_PORT=8082
      # This DSN points to the postgres container over the internal Docker network
      - LEDGER_DB_DSN=postgres://admin:password@postgres:5432/payments_db
    depends_on:
      - postgres # Ensures Postgres starts before the ledger service
    restart: unless-stopped

  # -------------------- KAFKA INFRASTRUCTURE --------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: payments_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: payments_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres-data:
    driver: local