global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:8081']
  - job_name: 'ledger-service'
    static_configs:
      - targets: ['ledger-service:8082']
  - job_name: 'transaction-orchestrator'
    static_configs:
      - targets: ['transaction-orchestrator:8083']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']
